# Application configuration values

# Twitter config value
	consumer_key = RxM3GDA9lQkioZNv3FRn5A
	consumer_secret = SuQUL0YfiW8I1FEz62joaYMatElcUIfpxxu3vDbnlzE
# Drop io Config value
	dropio_api = cb9cbc7c8c05a10bc613931f9c2d4fd029d9362d
	dropio_api_token = iudknm03s1
	dropio_admin_password = richerd123